language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"

env:
  - DJANGO="django==1.6"
  - DJANGO="django==1.5.5"

install:
  - pip install $DJANGO
  - export PYTHONPATH=.

script:
  - python flashpacker/runtests/runtests.py
